# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
